// Generated by KafeCMS on dev server start
// Do not edit manually

/// <reference types="kafecms/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "kafecms";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "kafecms" {
  interface KafeCMSCollections {
    pages: Page;
  }
}